apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexa-rag-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nexa-rag-api
  template:
    metadata:
      labels:
        app: nexa-rag-api
    spec:
      containers:
      - name: rag-api-container
        image: nexa-rag-app-2:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: OLLAMA_HOST
          value: "http://host.docker.internal:11434"